version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tivit
      MYSQL_DATABASE: tivit
      MYSQL_USER: tivit
      MYSQL_PASSWORD: tivit

  street_market_api:
    build: ./
    image: street_market_api
    depends_on:
      - mysql
    image: php:7.1-cli
    ports:
      - "8000:8000"
    volumes:
     - .:/var/www
    working_dir: /var/www
    stdin_open: true
    tty: true
