version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tivit
      MYSQL_DATABASE: tivit
      MYSQL_USER: tivit
      MYSQL_PASSWORD: tivit

  php:
    depends_on:
      - mysql
    image: php:7.1-cli
    ports:
      - "8000:8000"
    restart: always
    volumes:
     - .:/var/www
    working_dir: /var/www
    test: ["CMD", "curl", "-f", "http://localhost"]